
#!/bin/bash

while((1))
do
curl -H "Host: risk01.00.com" -v "http://127.1.1.1/1.html?x_usec=fdasfeqwf3DACDAEDQDVA23c%2fkeOVAKRoTpJ5TIi4SYD4SpFyNqEOWHN0NsEqDCSsECK7EpSJVZSJVZAJZZWBVYNfDeNyNrGZAHN0SYFcRIFyNq5ZAHN0SYFcRHcoYAWINpufRpRyNqzZAHN0SYJfSIJfRYVyNqzZVeN0RfNdSIVdSIRdlV%3d%3d" --user-agent "/html"
curl -H "Host: risk01.00.com" -v "http://127.1.1.1/1.html?x_usec=fdasfeqwf3DACDAEDQDVA23c%2fkeOVAKRoTpJ5TIi4SYD4SpFyNqEOWHN0NsEqDCSsECK7EpSJVZSJVZAJZZWBVYNfDeNyNrGZAHN0SYFcRIFyNq5ZAHN0SYFcRHcoYAWINpufRpRyNqzZAHN0SYJfSIJfRYVyNqzZVeN0RfNdSIVdSIRdlV%3d%3d" --user-agent "/html"
curl -H "Host: risk01.00.com" -v "http://127.1.1.1/1.html?x_usec=fdasfeqwf3DACDAEDQDVA23c%2fkeOVAKRoTpJ5TIi4SYD4SpFyNqEOWHN0NsEqDCSsECK7EpSJVZSJVZAJZZWBVYNfDeNyNrGZAHN0SYFcRIFyNq5ZAHN0SYFcRHcoYAWINpufRpRyNqzZAHN0SYJfSIJfRYVyNqzZVeN0RfNdSIVdSIRdlV%3d%3d" --user-agent "/html"
curl -H "Host: risk01.00.com" -v "http://127.1.1.1/1.html?x_usec=fdasfeqwf3DACDAEDQDVA23c%2fkeOVAKRoTpJ5TIi4SYD4SpFyNqEOWHN0NsEqDCSsECK7EpSJVZSJVZAJZZWBVYNfDeNyNrGZAHN0SYFcRIFyNq5ZAHN0SYFcRHcoYAWINpufRpRyNqzZAHN0SYJfSIJfRYVyNqzZVeN0RfNdSIVdSIRdlV%3d%3d" --user-agent "/html"
curl -H "Host: risk01.00.com" -v "http://127.1.1.1/1.html?x_usec=fdasfeqwf3DACDAEDQDVA23c%2fkeOVAKRoTpJ5TIi4SYD4SpFyNqEOWHN0NsEqDCSsECK7EpSJVZSJVZAJZZWBVYNfDeNyNrGZAHN0SYFcRIFyNq5ZAHN0SYFcRHcoYAWINpufRpRyNqzZAHN0SYJfSIJfRYVyNqzZVeN0RfNdSIVdSIRdlV%3d%3d" --user-agent "/html"
curl -H "Host: risk01.00.com" -v "http://127.1.1.1/1.html?x_usec=fdasfeqwf3DACDAEDQDVA23c%2fkeOVAKRoTpJ5TIi4SYD4SpFyNqEOWHN0NsEqDCSsECK7EpSJVZSJVZAJZZWBVYNfDeNyNrGZAHN0SYFcRIFyNq5ZAHN0SYFcRHcoYAWINpufRpRyNqzZAHN0SYJfSIJfRYVyNqzZVeN0RfNdSIVdSIRdlV%3d%3d" --user-agent "/html"

sleep 3
done
